---
name: dockerhub

on:
  push:
    branches:
      - 'master'
      - '5.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist:
          - bullseye
          - sid
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:${{ matrix.dist }}"
          push: true
          tags: kamailio/pkg-kamailio-docker:${{ github.ref_name }}-${{ matrix.dist }}
